services:
  - type: web
    name: qr-payment-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python qr.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: ACCOUNT_NUMBER
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
